### ISSUE TITLE
Don't mask NaN's, or make it a configuration option?

### ISSUE THREAD

**Issue by Gankro** [BurntSushi/byteorder#103]
Noticed this while looking at the codegen for deserializing a 4x4 f32 matrix with bincode, which otherwise *should* be a memcopy.

Having gone through the history of how this happened, the LLVM concerns are all bogus, it handles sNaN fine. I don't have much of an opinion on the platform-specific stuff, but at very least this seems like a reasonable feature-flag, or even target cfg thing. Certainly for my use-case, this mask does nothing.

**Comment by BurntSushi** [comment]
You can't just say "the LLVM concerns are bogus." Can you show it?

On Nov 12, 2017 21:36, "Alexis Beingessner" <notifications@github.com>
wrote:

Noticed this while looking at the codegen for deserializing a 4x4 f32
matrix with bincode, which otherwise *should* be a memcopy.

Having gone through the history of how this happened, the LLVM concerns are
all bogus, it handles sNaN fine. I don't have much of an opinion on the
platform-specific stuff, but at very least this seems like a reasonable
feature-flag, or even target cfg thing. Certainly for my use-case, this
mask does nothing.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/BurntSushi/byteorder/issues/103>, or mute the thread

**Comment by BurntSushi** [comment]
This should also be brought up with std as well, since from_bits has the
same masking behavior.

**Comment by Gankro** [comment]
Ah, I wasn't going to try to fix std since from_bits was stabilized documenting this behaviour, but I see now that it was a "may", so we can just change the impl without touching the documented contract.

**Comment by BurntSushi** [comment]
Exactly. That "may" was very intentional because we were very unsure of
ourselves, so we took the conservative route to leave it open to being
fixed for good. :)

**Comment by BurntSushi** [comment]
`byteorder 1.2.0` is on crates.io with this bug fixed.
