### ISSUE TITLE
add CI for testing on at least one big-endian target

### ISSUE THREAD

**Issue by BurntSushi** [BurntSushi/byteorder#106]
It turns out we had an improperly written test for big endian, which was discovered in #102 and fixed by @cuviper in #104.

I don't know exactly how to go about this, but PRs would be most welcome!

**Comment by Enet4** [comment]
I had a look at this issue, and I can picture two ways to tackle this:

- `mips64-unknown-linux-gnuabi64` is a by-default big-endian target which QEMU can virtualize. We could install QEMU and the necessary linux GNU cc/binutils, and configure cargo to run `qemu-mips64`.
- **or** we could just use [`cross`](https://crates.io/crates/cross), which does all of the above for you in a single command. :)

I tried both on one of my desktop machines, and it turns out that the former approach can be a headache, especially if the target architecture's binutils have to be compiled from sources. The `cross` project already provides the necessary containers for specific targets and automates all the heavy work with only the downside of relying on docker containers (which Travis already provides anyway!).

This appears to work on the [`safe-transmute`](https://github.com/nabijaczleweli/safe-transmute-rs/pull/10) crate, and I could do the same to `byteorder` if you'd like.

**Comment by BurntSushi** [comment]
@Enet4 Using `cross` would be fantastic! I would be very grateful if you were able to make it work with `byteorder`. :-)

**Comment by BurntSushi** [comment]
Closed by #115.
