### ISSUE TITLE
write_usize()

### ISSUE THREAD

**Issue by vext01** [BurntSushi/byteorder#132]
Hi,

Is there any reason why there's no `write_usize` function in byteorder?

Thanks

**Comment by BurntSushi** [comment]
Because the size of `usize` is platform dependent. Either convert it to a fixed size first, or use [`ByteOrder::write_uint`](https://docs.rs/byteorder/1.2.6/byteorder/trait.ByteOrder.html#tymethod.write_uint) or [`WriteBytesExt::write_uint`](https://docs.rs/byteorder/1.2.6/byteorder/trait.WriteBytesExt.html#method.write_uint).
