### ISSUE TITLE
`eprintln!` in build.rs requires rustc 1.19.0

### ISSUE THREAD

**Issue by tspiteri** [BurntSushi/byteorder#140]
I have a crate which is tested against rustc 1.18.0, and it uses byteorder during testing. Since byteorder 1.3.0 I got a failure because of the use of `eprintln!` in build.rs.

The bug was actually on my side, I've now fixed it to use byteorder ~1.2, as I kind of remember some policy where the minimum rustc version could be increased on minor version bumps. This issue is just to make sure that the change was intentional, as I didn't see the change documented and the only version I could find was 1.12.0 in .travis.yml.

Edit: Hmm, building passes with 1.12.0 but not with 1.18.0. I think this is because build.rs is not explicitly mentioned in Cargo.toml, and cargo only autodetects build.rs since 1.17.0.

**Comment by BurntSushi** [comment]
Great catch. This was definitely unintentional on my behalf. I trusted my tooling a bit too much to catch regressions like this, and completely overlooked the fact that `build.rs` wasn't auto-detected older versions of Rust.

> The bug was actually on my side, I've now fixed it to use byteorder ~1.2, as I kind of remember some policy where the minimum rustc version could be increased on minor version bumps.

That policy is indeed one I've used for other crates (such as `regex`), although I haven't applied that policy to byteorder. My hope is that we can continue to maintain compatibility since byteorder is heavily depended on and its implementation is simple enough that it should be possible. Certainly, we shouldn't be increasing the MSRV for things like `eprintln!` or struct field initialization. So thanks for that!

**Comment by BurntSushi** [comment]
@tspiteri Also, out of curiosity and just because I'm very interested in this topic, could you say why you are using an older version of rustc instead of tracking stable? (Getting use cases for older versions of rustc is really important if we ever hope to figure out how to solve the problems around it in the ecosystem.)

**Comment by tspiteri** [comment]
Just like you use 1.12.0, for testing! :) I test the Rug crate with version 1.18.0.

**Comment by BurntSushi** [comment]
@tspiteri Ah gotya! Great. Thanks!
