### ISSUE TITLE
Consider supporting outdated Rust versions to make bincode happy

### ISSUE THREAD

**Issue by kornelski** [BurntSushi/byteorder#179]
`bincode` has set their `byteorder` requirement to `>=1.3.0, < 1.4.0` in order to satisfy their minimum supported Rust version policy. [Unfortunately, such version ranges are painful in Cargo](https://github.com/bincode-org/bincode/issues/388), so the bincode-byteorder MSRV disagreement is causing conflicts for users of all Rust versions.

Could you keep `byteorder` 1.x compatible with Rust 1.18, so that `bincode` could relax its version requirement?

**Comment by BurntSushi** [comment]
Yeesh.

I don't care that much about using Rust 1.41.1 specifically. That is, I wouldn't mind rolling that back. But Rust 1.18 is a long ways back. I'd have to rollback the 2018 edition migration, for example.

On top of that, during the migration, I was finally able to use the endian conversion routines in std introduced in Rust 1.32. And that means [reduction of `unsafe`](https://github.com/BurntSushi/byteorder/commit/37daff6927988a85bb00eb6b1d83564d81279505). So with that alone, there are, IMO, material benefits for using an MSRV of at least Rust 1.32.

And if that weren't enough, `u128` was stabilized in Rust 1.26, which means supporting Rust 1.18 would require bringing back `build.rs` feature sniffing, which I dislike having.

On top of all of that, all of this work would be to resolve a likely non-existent problem.

If it were a matter of a few small things to make `byteorder` work on Rust 1.18, I'd oblige. I'm not unreasonable. But the above is too much. I have limited free time and I'm not going to spend it by rolling back improvements especially when it's caused by questionable maintenance practices.

I think you're easiest course of action is to `git checkout 1.3.4`, rename the crate to `byteorder-fork-because-msrv-bump-violates-semver` and send a PR to them. Or just inline the `byteorder` calls. I'd say you could just use the endian conversion routines in std, but alas, they were introduced a mere 2 years ago.
