### ISSUE TITLE
Add impl of `ReadBytesExt` and `WriteBytesExt` for `core2::io::Write`

### ISSUE THREAD

**Issue by AsafFisher** [BurntSushi/byteorder#183]
`core2` crate offers a more generic trait of `io::{Write, Read}`.
 Will it be fine if I add an impl for it?

**Comment by BurntSushi** [comment]
See: https://github.com/BurntSushi/byteorder/pull/184#issuecomment-962521784

**Comment by shymega** [comment]
Hi,

I have a [PR](https://github.com/liranringel/structure/pull/12) I've been collaborating on for [structure](https://github.com/liranringel/structure), which adds `no_std` support in order for my work on a few things - a serial protocol for an STM32 in a phone, and an XMODEM implementation in Rust. 

We've managed to get the PR partially compiling, using `core2`, but it's the `ReadBytesExt` and `WriteBytesExt` traits that are failing at the moment. This is the blocker.

@BurntSushi How would you recommend going about this? I'm commenting on this issue in the hope it could be re-opened.

**Comment by BurntSushi** [comment]
@shymega Not sure. I don't have a lot of context on your specific project, but `byteorder` isn't exactly a big crate. And some of its reason for its existence is now subsumed by the standard library's (for example) `u64::to_le_bytes` methods. Of course, this doesn't give you the higher level I/O convenience routines provided by `{Read,Write}BytesExt`, but if that's all you need, there really isn't that much there. You don't even need `unsafe` IIRC because you can just use std's routines. So I'd suggest you not even bother using `byteorder` at all.

**Comment by shymega** [comment]
Yeah, it's STM32 firmware that communicates over UART. The idea behind using `structure` (which in turn uses `byteorder` behind the scenes) was to pack the data like Python's `struct` module.

I suppose the question is, do we not use `byteorder`, or perhaps implement the higher-level I/O layer from `{Read,Write}BytesExt` in the `structure` crate instead.

The problem with that is that the STM32 firmware doesn't have `std`, and relies on `core` and `alloc`.

I'll give this some thought. I don't want to add dependencies to `byteorder` - I saw your comment on #184.

**Comment by BurntSushi** [comment]
I said `std`, but the integer routines for converting between raw bytes are provided by `core`.

I would personally just roll what you need inside `structure` as an implementation detail. We're probably talking about one or two line helper functions here.

**Comment by shymega** [comment]
Oh, right. Then that's perfect, we could probably reduce our dependency tree and implement it ourselves, I don't think we use `byteorder` extensively. This also helps with the STM32 side of things. Cheers, @BurntSushi - you were one of the first influences I had when I got into Rust. Ripgrep. Good to have your insight here.

**Comment by BurntSushi** [comment]
No problem. :-)

`byteorder` was a somewhat more important dependency before functions like [`u64::to_le_bytes`](https://doc.rust-lang.org/std/primitive.u64.html#method.to_le_bytes) were added to `core` because the _optimal_ implementation of those functions (with respect to performance) requires `unsafe`. But if you didn't care about `unsafe`, you could always [implement them using safe and portable code](https://commandcenter.blogspot.com/2012/04/byte-order-fallacy.html). Since this is Rust and:

1. People generally want the optimal thing with respect to perf and,
2. People generally want to minimize or centralize the use of `unsafe`

it follows that lots of folks found `byteorder` important. But now it is less so and that's a good thing.

`byteorder` does have bulk APIs like [`read_u64_into`](https://docs.rs/byteorder/latest/byteorder/trait.ReadBytesExt.html#method.read_u64_into) that cannot be implemented optimally without `unsafe`. But these are somewhat more niche APIs. And if you don't need the perf, you can still implement them using safe code with a smallish penalty.
