### ISSUE TITLE
Read Write for core

### ISSUE THREAD

**Issue by Ericson2314** [BurntSushi/byteorder#51]
@Tobba and I have worked on https://github.com/QuiltOS/core_io, a copy of Read and Write but with an associated error type to make it just need core. Perhaps it would be nice to (optionally) extend these traits for no_std users?

**Comment by BurntSushi** [comment]
@Ericson2314 I'd be willing to do so once `coreio` gains more traction.

**Comment by BurntSushi** [comment]
I'm going to close this but feel free to re-open if you think we should reconsider core-io!

**Comment by Ericson2314** [comment]
Sure. Once I have a version on crates.io polished a bit I'll ping this.

**Comment by whitequark** [comment]
@BurntSushi Chiming in as I'm using core_io a bunch: I would very much like this to happen, but until https://github.com/jethrogb/rust-core_io/issues/3 is resolved this would make the life of downstream crates *harder*.

**Comment by BurntSushi** [comment]
@whitequark That library is distinct from the one @Ericson2314 linked.

**Comment by whitequark** [comment]
@BurntSushi Oh. I'm much less happy with Ericson2314's library because it misses basic things (e.g. `BufReader`). I think the general direction of jethrogb's library (that is, mirroring std::io as closely as possible by being based on its codebase from the relevant libstd version directly) is correct, and from my audit I don't expect any other trouble after the two code-related issues I've opened are addressed.

**Comment by Ericson2314** [comment]
FWIW the only reason there is no BufReader is because I haven't implemented it yet.

**Comment by whitequark** [comment]
Yes, that you are reimplementing parts that are already well-tested by virtue of shipping in std::io also bothers me.
