### ISSUE TITLE
Extending integer types with a `.bytes()` method

### ISSUE THREAD

**Issue by jonas-schievink** [BurntSushi/byteorder#79]
I'm frequently in need of accessing individual Bytes of an integer (be it when writing emulators or implementing network protocols), and I thought this functionality would be a good addition to the byteorder crate (since it is inherently dependent on the byte order). One way it could work is by defining extension traits for all integer types that look like this:

```rust
trait U32Ext {
    fn bytes<B: ByteOrder>(self) -> [u8; 4];
}
```

It can be used like this:

```rust
let value = 123456i32;
let msb = value.bytes::<BigEndian>()[0];
let lsb = value.bytes::<BigEndian>()[3];

// These are equivalent:
let msb = value.bytes::<LittleEndian>()[3];
let lsb = value.bytes::<LittleEndian>()[0];
```

Of course, the methods must be marked `#[inline]` for reasonable performance (I've confirmed that these expressions are optimized properly, so only the computation for the accessed byte remains).

Thoughts?

**Comment by BurntSushi** [comment]
I feel like this is exactly the API that is already provided, but returns fixed sized arrays instead of requiring caller allocated slices.

I'm personally not big on making the API much bigger than what it is already, and I think this will add confusion as to what exactly callers are supposed to use.
