### ISSUE TITLE
Why does not `ByteOrder` not have a `read_u8` or `read_i8` function?

### ISSUE THREAD

**Issue by vitiral** [BurntSushi/byteorder#92]
It seems like they are really missing!

**Comment by BurntSushi** [comment]
What's the use case? If you're reading from `xs` where `xs` has type `&[u8]`, then `read_u8` is just `xs[0]` and `read_i8` is `xs[0] as i8`.

**Comment by vitiral** [comment]
Wouldn't that not be true if you're on a little endian  reading big endian (or vice versa)?

**Comment by BurntSushi** [comment]
@vitiral No? Endianness refers to the order of bytes that represent integers/floating point. If there's only one byte then there's only one ordering. :-)

**Comment by vitiral** [comment]
Oh... The bits don't also reverse in order? Man, I've been programming python too long (since my EE degree). 

I guess I would like it so that my deserialization doesn't implement anything custom, but maybe that's not a good enough reason :) 

Also, the io::Reader in new.rs has it, so it would be more consistent

**Comment by BurntSushi** [comment]
Yeah, I'm not seeing a compelling reason to add it.

**Comment by vitiral** [comment]
OK, thanks!

**Comment by regexident** [comment]
> Yeah, I'm not seeing a compelling reason to add it.

While adding methods for `u8` might not provide any _functional_ benefit I would argue that there is great benefit from being able to write code more consistency and thus more clearly.

There is no _functional_ reason for `u8` itself to provide `.to_be()` or `.to_be_bytes()` either (after all the stdlib comes with no numeric traits that would otherwise justify such methods for `u8`), yet it does. And so should `byteorder`, I think.

Take this piece of code that I'm dealing with right now for reading var-ints from a variably sized byte slice:

```rust
fn from_bytes(bytes: &[u8]) -> Self {
    let width = bytes.len();
    assert!(width <= 8);

    let mut padded_bytes: [u8; 8] = [0; 8];
    padded_bytes[(8 - width)..].copy_from_slice(bytes);

    match width {
        1..=1 => Self::U8(padded_bytes[7]),
        2..=2 => Self::U16(BigEndian::read_u16(&padded_bytes[6..])),
        3..=4 => Self::U32(BigEndian::read_u32(&padded_bytes[4..])),
        5..=8 => Self::U64(BigEndian::read_u64(&padded_bytes[0..])),
        _ => unreachable!(),
    }
}
```

If there was a `BigEndian::read_u8()`, then this code would be able to convey the underlying (consistent!) pattern much more clearly, while also looking much cleaner:

```rust
match width {
    1..=1 => Self::U8(BigEndian::read_u8(&padded_bytes[7..])),
    2..=2 => Self::U16(BigEndian::read_u16(&padded_bytes[6..])),
    3..=4 => Self::U32(BigEndian::read_u32(&padded_bytes[4..])),
    5..=8 => Self::U64(BigEndian::read_u64(&padded_bytes[0..])),
    _ => unreachable!(),
}
```

As a user there is no compelling reason for why one should have to write the `u8` case any different from the others.

One of the key benefits of using `byteorder` over hand-rolled bit-twiddling (in addition to the obvious ones like safety, etc) is being able to express things on a higher abstraction level and more consistently, reducing the likelihood of introducing bugs and regressions. The lack of `ByteOrder::read_u8()` & Co renders this benefit moot.

**Comment by tisonkun** [comment]
I agree with @regexident that `LE::read_i8` and `LE::read_u8` (and for BE) keep the API consistent.

Also there is subtle difference between `xs[i]` and `xs[i] as i8` that could be a caveat while if we provide both `read_i8` and `read_u8`, users can blindly use it and be safe.

cc @BurntSushi WDYT?

**Comment by BurntSushi** [comment]
I'd be open to a PR.

**Comment by tisonkun** [comment]
OK let me prepare one.

**Comment by tisonkun** [comment]
Backlink - https://github.com/BurntSushi/byteorder/pull/222

Also I'd prefer a new release for my project to use ><
